### ISSUE TITLE
Large variable files have a huge impact on performance

### ISSUE THREAD

**Issue by mlaurense** [dw/mitogen#117]
Not sure whether this is Mitogen related at all, whether it is something you're looking at improving but I'm gonna go ahead and post this here. Feel free to close this if you think this isn't related, or not something you can improve.

I've got a Yaml file, used to provision a webserver via --extra-vars "@filename.yml", which is ~ 10,000 lines. This contains the configuration for the websites running on it, and the SSL certificates for certain websites. The certificates consist of two (multiline) variables, a certificate chain and an ansible-vault encrypted private key. Total size of the Yaml is about 650 KB.

The total time to run the complete playbook (no changes made, as config is the same) is about 7m36.

As a test, I've split the variable file in two parts; a SSL part with all the certificates and private keys (7849 lines, 580 KB), and a config part (2249 lines, 63 KB). The task responsible for writing the SSL certificates to the destination host was moved to a separate playbook. When running the exact same configuration, but now split into two separate playbooks using the two separate variable files, the deployment takes 8 seconds for the SSL certificates, and 5m31 to run the other playbook. This is a huge difference.

I'm guessing it has something to do with the way ansible uses the variable files, and how all variables have to be available to, for example, the ansible template module. I've also tried to move the certificates out of the domains dictionary to their own dictionary in the same Yaml file, but this makes no difference in performance.

Examples of how our Yaml is formatted: 

With certificate in domains (original):
```
domains:
  test.local:
    username: user
    enabled: true
    nginx_conf: wordpress
    php_primary: php70
    ssl: true
    ssl_parameters:
      type: custom
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIGFzCCBP+gAwIBAgISBA0r/3g+5Yp157KVS74pqITQMA0GCSqGSIb3DQEBCwUA
        [ ... ]
      certificate_key: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        [ ... ]
      hsts: false
```

With certificate in a separate dict (makes no difference):
```
domains:
  test.local:
    username: user
    enabled: true
    nginx_conf: wordpress
    php_primary: php70
    ssl: true
    ssl_parameters:
      type: custom
      hsts: false
ssl_certificates:
  test.local:
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIGFzCCBP+gAwIBAgISBA0r/3g+5Yp157KVS74pqITQMA0GCSqGSIb3DQEBCwUA
      [ ... ]
    certificate_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      [ ... ]
```

Using separate files (makes huge difference):
```
domains:
  test.local:
    username: user
    enabled: true
    nginx_conf: wordpress
    php_primary: php70
    ssl: true
    ssl_parameters:
      type: custom
      hsts: false
```
```
ssl_certificates:
  test.local:
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIGFzCCBP+gAwIBAgISBA0r/3g+5Yp157KVS74pqITQMA0GCSqGSIb3DQEBCwUA
      [ ... ]
    certificate_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      [ ... ]
```
