### ISSUE TITLE
mitogen won't close synchronize tasks

### ISSUE THREAD

**Issue by vandlol** [dw/mitogen#140]
Same test case as in #139.

This time i'm using:

```
- name: Copy each Policy file to given webfilter
  synchronize:
    src: "{{ item.src }}"
    dest: /dest/dir
  with_filetree:
    - "/this/is/my/dir"
  when: item.state == 'file'
```

I know you shouldn't do this, but i need to since i want to flatten a directory structure into just one directoy on target host.

When I'm running this it the resulting playbook calls pile up

*snip from pstree*

`playboo─┬─ansible-playboo───499*[{ansible-playboo}]`
 And this number keeps growing.

This completely clogs my system
