### ISSUE TITLE
Setting ansible_python_interpreter within a play doesn't work

### ISSUE THREAD

**Issue by rouge8** [dw/mitogen#152]
Here's an awful construct from one of my playbooks. The server has a Python app, with a virtualenv at `{{ venv_bin }}` that already has psycopg2 installed. Rather than also install psycopg2 systemwide, I set `ansible_python_interpreter` to point to that virtualenv for any tasks that need it:

```yaml
- name: Store the original ansible_python_interpreter
  set_fact: original_ansible_python_interpreter={{ ansible_python_interpreter }}

- name: Use app virtualenv for Postgres tasks
  set_fact: ansible_python_interpreter={{ venv_bin }}/python

- name: Ensure the app DB user exists
  postgresql_user:
    db: postgres
    login_host: "{{ db_credentials.host }}"
    port: "{{ db_credentials.port }}"
    login_user: "{{ db_superuser }}"
    login_password: "{{ db_superuser_password }}"
    name: "{{ db_credentials.user }}"
    password: "{{ db_credentials.password }}"
    state: present

- name: Return to default Ansible python
  set_fact: ansible_python_interpreter={{ original_ansible_python_interpreter }}
```

The only trick necessary for this to be supported by Ansible without mitogen is adding `ansible_python_interpreter: /usr/bin/python` to group/hostvars.

With mitogen, this errors: `FAILED! => {"changed": false, "msg": "the python psycopg2 module is required"}` which looks like it did not switch to the new `ansible_python_interpreter` variable. I'm okay with the answer being "this is terrible and unsupported" :).

Here's the mitogen logs from that task. mitogen does not log anything for the `set_fact` tasks:

```
[pid 27834] 12:02:40 D mitogen: Context(10, u'ssh.env1-stage-web').call_async(<function run_module at 0x110db4aa0>, *('ansible.modules.database.postgresql.postgresql_user',), **{ARGS OMITTED})
[pid 27818] 12:02:40 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible_mitogen')
[pid 27818] 12:02:40 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible_mitogen')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible_mitogen.helpers')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible_mitogen.helpers')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.release')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.release')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.module_utils')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.module_utils.basic')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils._text')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils.parsing')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils.parsing.convert_bool')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils.pycompat24')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils.six')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils.basic')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.modules')
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.modules')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.modules.database')
[pid 27818] 12:02:41 D mitogen: pkgutil._get_module_via_pkgutil('ansible.modules.database') -> <pkgutil.ImpLoader instance at 0x10ea528c0>
[pid 27818] 12:02:41 D mitogen: _build_tuple('/Users/andy/gr/myproject/.tox/deploy/lib/python2.7/site-packages/ansible/modules/database/__init__.py', 'ansible.modules.database') -> ['influxdb', 'misc', 'mongodb', 'mssql', 'mysql', 'postgresql', 'proxysql', 'vertica']
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.modules.database')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.modules.database.postgresql')
[pid 27818] 12:02:41 D mitogen: pkgutil._get_module_via_pkgutil('ansible.modules.database.postgresql') -> <pkgutil.ImpLoader instance at 0x10ea52f80>
[pid 27818] 12:02:41 D mitogen: _build_tuple('/Users/andy/gr/myproject/.tox/deploy/lib/python2.7/site-packages/ansible/modules/database/postgresql/__init__.py', 'ansible.modules.database.postgresql') -> ['postgresql_db', 'postgresql_ext', 'postgresql_lang', 'postgresql_privs', 'postgresql_schema', 'postgresql_user']
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.modules.database.postgresql')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.modules.database.postgresql.postgresql_user')
[pid 27818] 12:02:41 D mitogen: pkgutil._get_module_via_pkgutil('ansible.modules.database.postgresql.postgresql_user') -> <pkgutil.ImpLoader instance at 0x10ea52128>
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.modules.database.postgresql.postgresql_user')
[pid 27818] 12:02:41 D mitogen: ModuleResponder(Router(Broker()))._on_get_module('ansible.module_utils.database')
[pid 27818] 12:02:41 D mitogen: pkgutil._get_module_via_pkgutil('ansible.module_utils.database') -> <pkgutil.ImpLoader instance at 0x10ea52878>
[pid 27818] 12:02:41 D mitogen: _send_load_module(mitogen.ssh.Stream(u'ssh.env1-stage-web'), 'ansible.module_utils.database')
[pid 27834] 12:02:41 D ansible_mitogen.connection: Call run_module('ansible.modules.database.postgresql.postgresql_user',) took 1995 ms
[pid 27834] 12:02:41 D mitogen: mitogen.core.Stream('unix_listener.27818').on_disconnect()
[pid 27818] 12:02:41 D mitogen: mitogen.core.Stream('unix_client.27834').on_disconnect()
[pid 27834] 12:02:41 D mitogen: Waker(Broker()).on_disconnect()
```
