### ISSUE TITLE
yum_repository in item loops causes repo duplication when used with mitogen

### ISSUE THREAD

**Issue by zswanson** [dw/mitogen#154]
ansible 2.4.3.0
  config file = /playbooks/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

ansible config:
[defaults]
inventory = ./inventory
display_skipped_hosts = False
log_path=./logs/
strategy_plugins = ./plugins/mitogen/ansible_mitogen/plugins/strategy
strategy = mitogen
callback_plugins = ./plugins/callbacks:~/.ansible/plugins/callback:/usr/share/ansible/plugins/callback
stdout_callback = anstomlog
retry_files_enabled = False

Using mitogen master cloned at b1bfe58095fbcbfdce8076c288d41af7e083ba58

I have a role task that calls yum_repository using with_items (also tested with_dict, same result) to populate a default list of repos and any 'extras' provided by the calling playbook. Expected behavior is one repo file per list item, with only that item in the repo file. With mitogen disabled, that's what I get. With mitogen enabled, each successive repo file in /etc/yum.repos.d/ contains all of the prior items in the loop. Simply enabling/disabling mitogen and re-running the playbook (deleting the created repos between each run) will demonstrate.

```
---

- hosts: localhost
  gather_facts: no
  become: true

  vars:

    repo_baseurl: "http://myurl.com"

    default_repos:
      - repo: demo-repo1
        description: Base software packages
        url: "{{repo_baseurl}}/repo1"
      - repo: demo-repo2
        description: Misc packages
        url: "{{repo_baseurl}}/repo2"

  tasks:

  - name: Create multiple yum repos
    yum_repository:
      name: '{{item.value.repo}}'
      http_caching: packages
      gpgcheck: no
      description: '{{item.value.description}}'
      state: present
      baseurl: '{{item.value.url}}'
      enabled: yes
    with_items: '{{ default_repos }}'
```

Expected outpout:
/etc/yum.repos.d/demo-repo1.repo
> [demo-repo1]
> baseurl = http://myurl.com/repo1
> enabled = 1
> gpgcheck = 0
> http_caching = packages
> name = Base software packages

/etc/yum.repos.d/demo-repo2.repo
> [demo-repo2]
> baseurl = http://myurl.com/repo2
> enabled = 1
> gpgcheck = 0
> http_caching = packages
> name = Misc packages

Actual output:
/etc/yum.repos.d/demo-repo1.repo
> [demo-repo1]
> baseurl = http://myurl.com/repo1
> enabled = 1
> gpgcheck = 0
> http_caching = packages
> name = Base software packages

/etc/yum.repos.d/demo-repo2.repo
> [demo-repo1]
> baseurl = http://myurl.com/repo1
> enabled = 1
> gpgcheck = 0
> http_caching = packages
> name = Base software packages
> [demo-repo2]
> baseurl = http://myurl.com/repo2
> enabled = 1
> gpgcheck = 0
> http_caching = packages
> name = Misc packages
