### ISSUE TITLE
ansible: env vars set in vars plugin not present in play for localhost

### ISSUE THREAD

**Issue by manicminer** [dw/mitogen#297]
This might sound strange, and may even be an unexpected behavior of Ansible to begin with.

I have a [vars plugin](https://github.com/manicminer/ansible-vars-plugin-aws) which [sets some environment variables](https://github.com/manicminer/ansible-vars-plugin-aws/blob/master/vars_plugins/aws.py#L97-L139) in-process. When I use the stock `linear` strategy, these vars are visible for plays running on `localhost`. When I use Mitogen, the vars are not visible.

## Reproducing

```python
# vars_plugins/test.py

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from ansible.plugins.vars import BaseVarsPlugin
import os

class VarsModule(BaseVarsPlugin):
    def __init__(self, *args):
        super(VarsModule, self).__init__(*args)
        os.environ['FOO'] = 'bar'

    def get_vars(self, loader, path, entities, cache=True):
        super(VarsModule, self).get_vars(loader, path, entities)
        return {}
```

```yaml
---
# playbook.yml

- hosts: localhost
  strategy: linear
  connection: local
  tasks:
    - shell: "env | grep FOO"

- hosts: localhost
  connection: local
  tasks:
    - shell: "env | grep FOO"
```

I fully admit this is abuse of a vars plugin, but I use it to set context-specific `AWS_*` variables, so that the correct AWS account is chosen based on some runtime logic.

Look forward to any feedback on this scenario! Is this sane? Fixable in Mitogen or antithetical to Mitogen's design? Thanks!
