### ISSUE TITLE
Mitogen 0.2.2 and Ansible 2.6.2

### ISSUE THREAD

**Issue by pierrehenrymuller** [dw/mitogen#330]
Hi,
With the latest version of Mitogen 0.2.2 and Ansible 2.6.2 a task with file module begin start and produce error : 

```
TASK [task : Remove suid/sgid] *************************************************************************************************************
ok: [host] => (item=/usr/bin/rcp)
ok: [host] => (item=/usr/bin/rlogin)
ok: [host] => (item=/usr/bin/rsh)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:   File "master:/usr/lib/python2.7/dist-packages/ansible/modules/files/file.py", line 395, in ensure_file_attributes
fatal: [host]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

```
The task is : 
```
- name: Remove suid/sgid                                                                                                                           
  file:                                                                                                                                                                             
    path: '{{ item }}'                                                                                                                                                              
    mode: 'a-s'                                                                                                                                                                     
    state: file                                                                                                                                                                     
    follow: yes                                                                                                                                                                     
  failed_when: false                                                                                                                                                                
  with_items:                                                                                                                                                                       
    - '{{ os_security_suid_sgid_system_blacklist }}'                                                                                                                                
```
List are like this : 

```
os_security_suid_sgid_system_blacklist:                                                                                                                                             
  - '/usr/bin/rcp'                                                                                                                                                                  
  - '/usr/bin/rlogin'                                                                                                                                                               
  - '/usr/bin/rsh'                                                                                                                                                                  
  - '/usr/libexec/openssh/ssh-keysign'                                                                                                                                              
  - '/usr/lib/openssh/ssh-keysign'
  - ...
```
I have a doubt, is Mitogen compatible Ansible 2.6? The only place I found about version is in Noteworthy Differences part. Can you confirm?
Thanks
