### ISSUE TITLE
[ssh] make TTYs optional

### ISSUE THREAD

**Issue by dw** [dw/mitogen#337]
There is a limit on the maximum number of TTYs many operating systems can allocate. By default on Linux, this is 4096. Given a run targetting more than 4000 machines, TTYs will be easily exhausted, and so using them should be made optional when typing passwords is not necessary.

**Comment by dw** [comment]
Upstream Ansible already supports a flag we can reuse:

````
      use_tty:
        version_added: '2.5'
        default: 'yes'
        description: add -tt to ssh commands to force tty allocation
        env: [{name: ANSIBLE_SSH_USETTY}]
        ini:
        - {key: usetty, section: ssh_connection}
        type: bool
        vars:
          - name: ansible_ssh_use_tty
            version_added: '2.7'
````
