### ISSUE TITLE
[ansible-mitogen] 'delegate_to' logic

### ISSUE THREAD

**Issue by fdutheil** [dw/mitogen#340]
Hi, let's start by saying this project is quite impressive (goals, design, initial documentation). I spent half a day reading, understanding (or trying to) and trying to get it working as an alternative to the sshjail plugin (great either, in other aspects).
Anyway, I got pretty much what I wanted: **H** is a freebsd host with jails, like the **J** jail. As I use sudo, I had to use mitogen_sudo, which was kind of a travel :). Anyway, as I said, my existing playbooks workds on **J** and its siblings. Except one: at some point, I run a command on an external host **E** (which is OK when tested with ansible *ping* module) that renew many TLS certificates in one run, thus I us the ansible delegate_to logic to achive that.

Let's see:
```
- name: (re)generate TLS certificates
  hosts: all_jails (including [J])
  gather_facts: no
  vars:
    force_cert_renewal: "{{ tls_force|default(False)|bool|ternary('--force','') }}"
  tasks:
    - name: Request a TLS certificate from LE with dehydrated
      command: /home/me/progs/dehydrated/dehydrated -c {{ force_cert_renewal }} -a {{ tls_algo }} -d {{ tls_fqdn }} --lock-suffix {{ tls_fqdn }}
      async: 1800
      poll: 20
      delegate_to: [E]
```

And that's where the logic is strange to me, as I look at the error I get:
```
TASK [Request a TLS certificate from LE with dehydrated] *****************************************
fatal: [J]: UNREACHABLE! => {"changed": false, "msg": "error occurred on host [H]: Host key checking is enabled, and SSH reported an unrecognized or mismatching host key.", "unreachable": true}
```
As I understand, **H** (hosting **J**) is trying to connect via SSH to **E**, when that should be the ansible control machine that should do it. OK, may that be one case where mitogen differs from ansible vanilla behaviour? I've defined a simple "tree" of connections (meaning my control machine can reach them all), and not a complete P2P web allowing any connection from any point. Is it fundamentally condemn to fail, from the mitogen point of view? Because I don't plan to allow J or H to reach E anytime soon (different security networks).

Versions information:
- **H**: FreeBSD 11.x/python2.7
- **J**: same
- **E**: OpenBSD 6.2/python2.7
- *Control Machine*: gentoo/python2.7/python3.6/ansible 2.5.6, tested both 0.2.2 and latest master version of mitogen

Meanwhile, I'll continue to dig.
