### ISSUE TITLE
freeze on task with xml module

### ISSUE THREAD

**Issue by LuckySB** [dw/mitogen#454]
* Have you tried the latest master version from Git?
yes 

* Mention your host and target OS and versions
Centos 7.5 on host and Centos 7.6 on target
* Mention your host and target Python versions
python 2.7 on host and target

Hang up with mitogen v0.2.3, crash with mitogen from master branch

Role to create kvm VM: 
Ansible task with xml module
```
- name: Get pool type (xml)
  xml:
    path: "/etc/libvirt/storage/{{ item.pool_name }}.xml"
    xpath: "/pool"
    content: attribute
    attribute: type
  when: >
    (item.name not in kvm_existing_vms.list_vms and item.state|d('running') != 'undefined') or
    (item.name in kvm_existing_vms.list_vms and item.state|d('running') == 'undefined')
  with_items: "{{ kvm_vm }}"
  loop_control:
    label: "{{ item.pool_name }}"
  register: kvm_pool_xml_type
  changed_when: kvm_pool_xml_type.matches[0].pool.type is defined
```
Error on /var/log/messages
```
Dec 13 13:41:55 bigtest kernel: python[20653]: segfault at 10 ip 00007f1e55bd8afd sp 00007ffd2f5e2550 error 4 in etree.so[7f1e558a1000+547000]
```

ansible output -vvvv

[log.txt](https://github.com/dw/mitogen/files/2676790/log.txt)
