### ISSUE TITLE
`ec2_group` module doesn't work with Mitogen 0.2.4

### ISSUE THREAD

**Issue by jbscare** [dw/mitogen#536]
With Mitogen 0.2.4, this playbook:

```yaml
- hosts: localhost
  tasks:
    - ec2_group:
        name: jbstest
        description: JBS testing
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        rules: []
        rules_egress: []
```
Produces this output:

```
TASK [ec2_group] ***************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "boto3 required for this module"}
```

It works fine with Mitogen 0.2.2; it fails with 0.2.4, whether the security group already exists or not.

Here's a log with `-vvv`: [ansible.log](https://github.com/dw/mitogen/files/2852850/ansible.log)

**Comment by dw** [comment]
Same as #511

**Comment by dw** [comment]
Somehow explicit localhost's python_path has been broken. To confirm, do you have 'localhost' listed explicitly in your inventory? I see here by removing it (and receiving the default implicit localhost Ansible provides), the problem disappears.

This is almost certainly due to the python_path changes done during the delegate_to fiasco.

**Comment by jbscare** [comment]
Since you asked on #511, I tried your suggestion there; neither of `-e ansible_python_interpreter=python` nor `-e ansible_python_interpreter=/usr/bin/python` change the behavior for me.

We do have `localhost` explicitly in our inventory, so that we can set three host variables:
```yaml
  localhost: 
    ansible_connection: local 
    readiness: ready 
    stack: prod 
```
Does the default localhost go via SSH rather than local?

(The other two variables are things that normally get set via the ec2.py inventory plugin, but localhost doesn't come from EC2, of course.)
