### ISSUE TITLE
ansible k8s fails with mitogen

### ISSUE THREAD

**Issue by varac** [dw/mitogen#569]
I'm using this ansible k8s ansible resource:

```
- name: Install Tiller                                                                                                                                                                   
  tags:                                                                                                                                                                                  
    - tiller                                                                                                                                                                             
  k8s:                                                                                                                                                                                   
    state: present                                                                                                                                                                       
    definition: "{{ lookup('file', 'k8s-config/tiller-permissions.yml') }}"                                                                                                              
```  

It works fine without mitogen, but fails once I use mitogen:

```
  msg: This module requires the OpenShift Python client. Try `pip install openshift`
	to retry, use: --limit @/builds/openappstack/bootstrap/test/bootstrap.retry
```

See attached verbose log for more details.

* Which version of Ansible are you running? 

2.7.9

* Is your version of Ansible patched in any way? 

No

* Are you running with any custom modules, or `module_utils` loaded?

No

* Have you tried the latest master version from Git?

Do you mean ansible master or mitogen master ? I didn't try any.

* Do you have some idea of what the underlying problem may be?

No

* Mention your host and target OS and versions

Host: [Docker image](docker.greenhost.net/openappstack/bootstrap/bootstrap-ci:latest) based on alpine:3.9
Target: Ubuntu 18.04

* Mention your host and target Python versions

Host: 3.6.8
Target: 3.6.7

* If reporting any kind of problem with Ansible, please include the Ansible
  version along with output of "ansible-config dump --only-changed".

```
DEFAULT_CALLBACK_WHITELIST(/builds/openappstack/bootstrap/test/ansible.cfg) = ['profile_tasks', 'timer']
DEFAULT_HOST_LIST(/builds/openappstack/bootstrap/test/ansible.cfg) = ['/builds/openappstack/bootstrap/test/inventory.yml']
DEFAULT_STDOUT_CALLBACK(/builds/openappstack/bootstrap/test/ansible.cfg) = yaml
DEFAULT_STRATEGY(/builds/openappstack/bootstrap/test/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/builds/openappstack/bootstrap/test/ansible.cfg) = ['/builds/openappstack/bootstrap/test/plugins/mitogen-0.2.6/ansible_mitogen/plugins/strategy']
```
[mitogen-k8s.log](https://github.com/dw/mitogen/files/2985757/mitogen-k8s.log)
