### ISSUE TITLE
delegate_facts from a container's host to a container creates a cycle

### ISSUE THREAD

**Issue by jimmymccrory** [dw/mitogen#584]
I'm helping with the OpenStack-Ansible integration and we're currently running into a error when a host tries to delegate its facts to a container that it's hosting.

I've been able to reproduce this with a much simpler playbook and inventory than an OpenStack-Ansible deployment would be using.

playbook
```
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: install lxc
      apt:
        name: python-lxc,lxc,lxc-templates
        state: present
    - name: create a container
      lxc_container:
        name: test-container
        state: started
        template: ubuntu
        template_options: --packages python
    - name: gather and delegate facts
      setup:
        gather_subset: '!all:hardware'
      delegate_to: test-container
      delegate_facts: true
```
inventory
```
all:
  hosts:
    test-container:
      ansible_hostname: test-container
      mitogen_container_name: test-container
      mitogen_kind: lxc
      mitogen_via: localhost
      ansible_connection: setns
```
```
TASK [gather and delegate facts] *******************************************************************************************************************************************************************************************************
task path: /tmp/test.yml:15
[task 26394] 11:27:07.272509 D mitogen: unix.connect(path='/tmp/mitogen_unix_etAT4g.sock')
[task 26394] 11:27:07.273311 D mitogen: unix.connect(): local ID is 1004, remote is 0
[mux  26323] 11:27:07.273296 D mitogen: mitogen.unix.Listener('/tmp/mitogen_unix_etAT4g.sock'): accepted mitogen.core.Stream('unix_client.26394')
[task 26394] 11:27:07.278025 D mitogen: mitogen.core.Stream('unix_listener.26323').on_disconnect()
[mux  26323] 11:27:07.278400 D mitogen: mitogen.core.Stream('unix_client.26394').on_disconnect()
[task 26394] 11:27:07.278428 D mitogen: Waker(Broker(0x7f21e3ea6dd0) rfd=9, wfd=10).on_disconnect()
[task 26394] 11:27:07.278958 D mitogen: Router(Broker(0x7f21e3ea6dd0)): stats: 0 module requests in 0 ms, 0 sent (0 ms minify time), 0 negative responses. Sent 0.0 kb total, 0.0 kb avg.
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "mitogen_via=None of localhost creates a cycle (localhost -> localhost)",
    "unreachable": true
}
	to retry, use: --limit @/tmp/test.retry
```

Both the host and container are running Ubuntu 18.04.2 and Python 2.7.15rc1

```
ansible 2.7.10
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```
