### ISSUE TITLE
Ansible 2.8 AttributeError: 'module' object has no attribute 'id'

### ISSUE THREAD

**Issue by Rizzly** [dw/mitogen#592]
[Execution log for playbook below](https://github.com/dw/mitogen/files/3228302/ansiblemitogen2.log)

* Which version of Ansible are you running?
2.8.0, the issue does not occur with 2.7.9
* Is your version of Ansible patched in any way?
No.
* Are you running with any custom modules, or `module_utils` loaded?
No, the problem occurs even when any custom modules are disabled.

* Have you tried the latest master version from Git?
Of mitogen, yes. Of ansible, no.
* Do you have some idea of what the underlying problem may be?
Not really, except for the obvious fact that `id` is missing when using mitogen.
* Mention your host and target OS and versions
Debian 9 on the host and ubuntu 16.04 on the target
* Mention your host and target Python versions
2.7.13 on the host and 2.7.12 on the target

The issues can be reproduced by running the following playbook:
```
- name: test ansible 2.8 id missing
  hosts: host.com
  tasks:
    - user:
        name: '{{ ansible_env.SUDO_USER|default(ansible_env.USER) }}'
        createhome: yes
      become_user: root
```
