### ISSUE TITLE
Failed to write to file .ssh/known_hosts: [Errno 2] No such file or directory: '.ssh/tmpupg6c51q'

### ISSUE THREAD

**Issue by sscherfke** [dw/mitogen#639]
I have task the that runs the `known_hosts` module with a loop and multiple items.  

It mostly works, except when I run the playbook with mitogen from within a centos7 docker container (e.g., in a CI/CD pipeline).  Here is the "works/fails" matrix I tested:

mitogen | Fedora WS | centos7 docker
--------|-----------|---------------
**yes** | works | fails
**no** | works | works

System facts:

- ansible 2.8.3
- mitogen 0.2.8 and git master
- centos7 Docker container
- Target system: Python: 3.6 (system)
- Where ansible is run: Python 3.7 (conda)

The minimal playbook:

```yaml
# hosts.yaml
all:
  hosts:
    myhost:
      ansible_host: host.example.com
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    ansible_user: myuser
```
```yaml
# debug.yaml
- hosts: myhost
  gather_facts: False  # Speed-up deployments since we don't need these facts
  tasks:
    - name: Add/update public keys in kown_hosts
      known_hosts:
        name: "{{ item.host }}"
        key: "{{ item.key }}"
        path: .ssh/known_hosts
      loop:
       - {host: a, key: 'a,1.2.3.4 ecdsa-sha2-nistp256 ABCD1234'}
       - {host: b, key: 'b,5.6.7.8 ecdsa-sha2-nistp256 EFGH5678'}
```

The first item always works, but from the second item on, it fails like this:
```
...
TASK [Add/update public keys in kown_hosts] *************************************************************************
ok: [myhost] => (item={'host': 'a', 'key': 'a,1.2.3.4 ecdsa-sha2-nistp256 ABCD1234'})
failed: [myhost] (item={'host': 'b', 'key': 'b,5.6.7.8 ecdsa-sha2-nistp256 EFGH5678'}) => {"ansible_loop_var": "item", "changed": false, "item": {"host": "b", "key": "b,5.6.7.8 ecdsa-sha2-nistp256 EFGH5678"}, "msg": "Failed to write to file .ssh/known_hosts: [Errno 2] No such file or directory: '.ssh/tmpupg6c51q'"}
```
The the log with `-vvv` is attached: [ansible.log](https://github.com/dw/mitogen/files/3534103/ansible.log)

**Comment by dw** [comment]
This is a wonderfully concise bug report, thanks for for that. That it is a temp file suggests something may be going wrong with Mitogen's "automatic leaked file descriptor cleanup" logic, but possibly it could be Yet Another Temp File issue due to the compatibility insanity inherited from Ansible :)

I'll try to setup a repro for this later, if it's the auto cleanup code it's probably a 1 liner fix. Thanks for reporting!

**Comment by dw** [comment]
Actually looking at the log, I've a feeling it's maybe the current working directory. Don't have a fix for you yet, but I'm wondering if you change '.ssh/...' in your playbook to '~/.ssh/...', does the problem abate

There are multiple chdirs between tasks, one added just in 0.2.8. It might be related

**Comment by sscherfke** [comment]
Yes, chaning the task to 
```yaml
    - name: Add/update public keys in kown_hosts                                                                                                                                  
      known_hosts:                                                                                                                                                                
        name: "{{ item.host }}"                                                                                                                                                   
        key: "{{ item.key }}"                                                                                                                                                     
        path: "/home/{{ ansible_user }}/.ssh/known_hosts"                                                                                                                         
      loop:                                                                                                                                                                       
       - {host: a, key: 'a,1.2.3.4 ecdsa-sha2-nistp256 ABCD1234'}                                                                                                                 
       - {host: b, key: 'b,5.6.7.8 ecdsa-sha2-nistp256 EFGH5678'} 
```
fixes / works around the issue indeed.
